<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>pfinal_nav2_hri_manager</name>
  <version>0.3.0</version>
  <description>Proyecto final ROS2 Jazzy: orquestador FSM Nav2 + HRI (simple_hri) + YOLO</description>

  <maintainer email="student@university.es">student</maintainer>
  <license>Apache-2.0</license>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>nav2_msgs</depend>
  <depend>action_msgs</depend>
  <depend>vision_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>ament_index_python</depend>

  <depend>hri_client</depend>
  <depend>simple_hri_interfaces</depend>
  <exec_depend>simple_hri</exec_depend>
  <exec_depend>sound_play</exec_depend>
  <exec_depend>camera</exec_depend>
  <exec_depend>yolo_bringup</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
