# config/waypoints.yaml
# Coordenadas en metros en el frame 'map'.
# Obtén los valores con RViz (2D Nav Goal) o con la fórmula:
#   x = (pixel_x - origin_x) * resolution
#   y = (origin_y - pixel_y) * resolution
# donde origin_x, origin_y y resolution vienen de tu map.yaml

waypoints:
  centro:
    x: 1.6266
    y: 4.28702
    theta: 0.604198   # radianes

  puerta:
    x: 1.37
    y: 7.01
    theta: -0.745

  papelera:
    x: 1.73421
    y: 5.89065
    theta: -0.745802

  punto_a: # puerta
    x: 1.37
    y: 7.01
    theta: -0.745

  punto_b: # pasillo
    x: 3.26283
    y: 8.44936
    theta: 2.1542  # 180 grados
